RULES = {
    # Food & Dining
    "ZOMATO": "Food",
    "SWIGGY": "Food",
    "DOMINO": "Food",
    "PIZZA HUT": "Food",
    "KFC": "Food",
    "MCDONALD": "Food",
    "BURGER KING": "Food",
    "SUBWAY": "Food",
    "STARBUCKS": "Food",
    "CAFE COFFEE DAY": "Food",
    "CHAAYOS": "Food",
    "BARBEQUE NATION": "Food",
    "HALDIRAM": "Food",
    "MITHAIWALA": "Food",      # catches SIRVI BANDHU MITHAIWALA AND FOOD MALL etc.
    "FOOD MALL": "Food",
    "RESTAURANT": "Food",
    "HOTEL": "Food",
    "DHABA": "Food",
    "CHICKEN CENTRE": "Food",
    "CHICKEN CENTER": "Food",
    "CHICKEN SHOP": "Food",
    "BAKERY": "Food",
    "SWEETS": "Food",
    "CANTEEN": "Food",
    "MESS": "Food",
    "BIRYANI": "Food",
    "JUICE": "Food",
    "TEA": "Food",

    # Groceries & Daily Needs
    "BLINKIT": "Groceries",
    "BIGBASKET": "Groceries",
    "DUNZO": "Groceries",
    "ZEPTO": "Groceries",
    "DMART": "Groceries",
    "RELIANCE FRESH": "Groceries",
    "MORE SUPERMARKET": "Groceries",
    "EASYDAY": "Groceries",
    "SUPERSTORE": "Groceries",
    "SUPERMARKET": "Groceries",
    "GENERAL STORE": "Groceries",
    "KIRANA": "Groceries",
    "MULTISTORE": "Groceries",     # catches SHREE BALAJI MULTISTORE etc.
    "PROVISION": "Groceries",
    "BHANDAR": "Groceries",
    "VEGETABLES": "Groceries",
    "FRUIT": "Groceries",

    # Medical & Healthcare
    "ARRIVA MEDICAL": "Medical",
    "PATEL CHEMIST": "Medical",
    "APOLLO PHARMACY": "Medical",
    "MEDPLUS": "Medical",
    "NETMEDS": "Medical",
    "1MG": "Medical",
    "PHARMEASY": "Medical",
    "CHEMIST": "Medical",
    "PHARMACY": "Medical",
    "MEDICAL": "Medical",
    "HOSPITAL": "Medical",
    "CLINIC": "Medical",
    "DIAGNOSTIC": "Medical",
    "LAB": "Medical",
    "DOCTOR": "Medical",
    "HEALTH": "Medical",
    "NURSING": "Medical",

    # Fuel & Transport
    "INDIAN OIL": "Fuel",
    "HP PETROL": "Fuel",
    "BHARAT PETROLEUM": "Fuel",
    "HPCL": "Fuel",
    "BPCL": "Fuel",
    "IOCL": "Fuel",
    "PETROL": "Fuel",
    "DIESEL": "Fuel",
    "FUEL": "Fuel",
    "OLA": "Transport",
    "UBER": "Transport",
    "RAPIDO": "Transport",
    "IRCTC": "Transport",
    "INDIAN RAILWAY": "Transport",
    "REDBUS": "Transport",
    "MAKEMYTRIP": "Transport",
    "GOIBIBO": "Transport",
    "CLEARTRIP": "Transport",
    "YATRA": "Transport",
    "PARKING": "Transport",
    "FASTAG": "Transport",
    "TOLL": "Transport",
    "AUTO": "Transport",
    "CAB": "Transport",
    "TAXI": "Transport",

    # Shopping & E-commerce
    "AMAZON": "Shopping",
    "FLIPKART": "Shopping",
    "MYNTRA": "Shopping",
    "AJIO": "Shopping",
    "NYKAA": "Shopping",
    "MEESHO": "Shopping",
    "SNAPDEAL": "Shopping",
    "CROMA": "Shopping",
    "RELIANCE DIGITAL": "Shopping",
    "VIJAY SALES": "Shopping",
    "DECATHLON": "Shopping",
    "LIFESTYLE": "Shopping",
    "WESTSIDE": "Shopping",
    "PANTALOONS": "Shopping",

    # Entertainment & Subscriptions
    "NETFLIX": "Entertainment",
    "HOTSTAR": "Entertainment",
    "DISNEY": "Entertainment",
    "AMAZON PRIME": "Entertainment",
    "SPOTIFY": "Entertainment",
    "YOUTUBE": "Entertainment",
    "BOOKMYSHOW": "Entertainment",
    "PVR": "Entertainment",
    "INOX": "Entertainment",
    "CINEPOLIS": "Entertainment",
    "ZEE5": "Entertainment",
    "SONYLIV": "Entertainment",

    # Utilities & Bills
    "ELECTRICITY": "Utilities",
    "MSEDCL": "Utilities",
    "MAHADISCOM": "Utilities",
    "BESCOM": "Utilities",
    "TATA POWER": "Utilities",
    "ADANI ELECTRICITY": "Utilities",
    "GAS": "Utilities",
    "MAHANAGAR GAS": "Utilities",
    "IGL": "Utilities",
    "WATER BILL": "Utilities",
    "BROADBAND": "Utilities",
    "ACT FIBERNET": "Utilities",
    "JIOFIBER": "Utilities",
    "AIRTEL": "Utilities",
    "VODAFONE": "Utilities",
    "BSNL": "Utilities",
    "MOBILE RECHARGE": "Utilities",
    "DTH": "Utilities",
    "TATA SKY": "Utilities",
    "DISH TV": "Utilities",

    # Education
    "BYJU": "Education",
    "UNACADEMY": "Education",
    "VEDANTU": "Education",
    "COURSERA": "Education",
    "UDEMY": "Education",
    "SCHOOL": "Education",
    "COLLEGE": "Education",
    "UNIVERSITY": "Education",
    "COACHING": "Education",
    "TUITION": "Education",
    "FEE": "Education",

    # Finance & Banking
    "EMI": "Finance",
    "LOAN": "Finance",
    "INSURANCE": "Finance",
    "LIC": "Finance",
    "HDFC LIFE": "Finance",
    "ICICI PRUDENTIAL": "Finance",
    "SBI LIFE": "Finance",
    "MUTUAL FUND": "Finance",
    "ZERODHA": "Finance",
    "GROWW": "Finance",
    "COIN": "Finance",
    "CREDIT CARD": "Finance",
    "CREDIT CARD BILL": "Finance",
    "INVESTMENT": "Finance",
    "SIP": "Finance",

    # Wallet top-ups & self-transfers
    "TOP-UP": "Transfer",
    "TOPUP": "Transfer",
    "ADD MONEY": "Transfer",
    "WALLET": "Transfer",
    "UPI LITE": "Transfer",
    "CASHBACK": "Transfer",
    "REFUND": "Transfer",
    "PAYTM": "Transfer",
    "PHONEPE WALLET": "Transfer",
    "LOAD MONEY": "Transfer",
}


def rule_based_category(merchant: str):
    for key, category in RULES.items():
        if key in merchant:
            return category
    return None
